### ISSUE TITLE
Information item management

### ISSUE THREAD

**Issue by OscarGarayar** [OpenSource-DeltaTech-SW57/DiligenceTech-WebApp#4]

**Comment by coffeeisknowledge** [comment]
![Image](https://github.com/OpenSource-DeltaTech-SW57/DiligenceTech-WebApp/assets/89022106/734ffef1-33c4-4e18-80c0-fa30fdb66e6b)

Se implemento la logica y servicios de todos los componentes de la aplicacion. En donde se establecio un crud para todos los componentes del dominio que lo necesitaron.
